# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Saas


class _Gsuite(_Saas):
    _type = "gsuite"
    _icon_dir = "resources/saas/gsuite"


class Calendar(_Gsuite):
    _icon = "calendar.png"


# Aliases
