# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Generic


class _Cms(_Generic):
    _type = "cms"
    _icon_dir = "resources/generic/cms"


class Ghost(_Cms):
    _icon = "ghost.png"


# Aliases
