# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Generic


class _Geometry(_Generic):
    _type = "geometry"
    _icon_dir = "resources/generic/geometry"


class Arrow(_Geometry):
    _icon = "arrow.png"


class Change(_Geometry):
    _icon = "change.png"


class Zigzag(_Geometry):
    _icon = "zigzag.png"


# Aliases
