# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Generic


class _Visualization(_Generic):
    _type = "visualization"
    _icon_dir = "resources/generic/visualization"


class Graph(_Visualization):
    _icon = "graph.png"


# Aliases
